# -*- coding: utf-8 -*-
"""BaiTapTrenLopTuan01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dFyr3YYZYYnfKOBCA0NEgGuBQtYLKimx
"""

#cau1
a = float(input("Nhập giá trị a: "))
b = float(input("Nhập giá trị b: "))
tong = a + b
print(f"Tổng của a và b là: {tong}")
hieu = a - b
print(f"Hiệu của a và b là: {hieu}")
tich = a * b
print(f"Tích của a và b là: {tich}")
if b != 0:
    thuong = a / b
    print(f"Thương của a và b là: {thuong}")
else:
    print("Không thể chia cho 0.")

#cau2
chuoi = "Hello World"
kytu_can_lay = chuoi[2:5]
print(f"Các ký tự từ chỉ số 2 đến 4: {kytu_can_lay}")

#cau3
chuoi_goc = " Hello World"
chuoi_sau_khi_xoa_khoang_trang = chuoi_goc.strip()
print(f"Chuỗi gốc: '{chuoi_goc}'")
print(f"Chuỗi sau khi xóa khoảng trắng: '{chuoi_sau_khi_xoa_khoang_trang}'")
chuoi_hoa = chuoi_sau_khi_xoa_khoang_trang.upper()
chuoi_thuong = chuoi_sau_khi_xoa_khoang_trang.lower()
print(f"Chuỗi dạng hoa: {chuoi_hoa}")
print(f"Chuỗi dạng thường: {chuoi_thuong}")
chuoi_thay_the = chuoi_sau_khi_xoa_khoang_trang.replace('H', 'J')
print(f"Chuỗi sau khi thay 'H' bằng 'J': {chuoi_thay_the}")

#cau4
a = float(input("Nhập giá trị a: "))
b = float(input("Nhập giá trị b: "))

if a > b:
    print("Hello World!")
else:
    print("a không lớn hơn b.")

#cau5
a = float(input("Nhập giá trị a: "))
b = float(input("Nhập giá trị b: "))

if a == b:
    print("Yes")
else:
    print("No")

#cau6
a = float (input("Nhập giá trị a:"))
b = float (input("Nhập giá trị b"))
if a == b:
  print(1)
elif a > b:
  print(2)
else:
  print(3)

#cau7
a = float(input("Nhập giá trị a: "))
b = float(input("Nhập giá trị b: "))
d = float(input("Nhập giá trị d: "))

if a == b and b == d:
    print("Hello World!")
else:
    print("Điều kiện a = b và b = d không được thỏa mãn.")

#cau8
a = float(input("Nhập giá trị a: "))
b = float(input("Nhập giá trị b: "))
c = float(input("Nhập giá trị c: "))
d = float(input("Nhập giá trị d: "))

if a == b or c == d:
    print("Hello World!")
else:
    print("Điều kiện a = b hoặc c = d không được thỏa mãn.")

#cau9
a = float(input("Nhập giá trị a:"))
b = float(input("Nhập giá trị b:"))
print ('Yes') if a > b print ('No') else

a = float(input("Nhập giá trị a: "))
b = float(input("Nhập giá trị b: "))
print("A") if a > b else print("=") if a == b else print("B")

"""Lỗi 'NameError: name 'a' is not defined' xảy ra vì các biến 'a' và 'b' chưa được định nghĩa trước khi sử dụng trong câu lệnh print có điều kiện. Để khắc phục, chúng ta cần khai báo và gán giá trị cho 'a' và 'b' trong ô này."""

#cau11
n = int(input("Nhập số lượng phần tử của mảng a: "))
a = []
for i in range(n):
    element = int(input(f"Nhập phần tử thứ {i+1} cho mảng a:"))
    a.append(element)
print(f"Mảng a: {a}")
b = [element for element in a if element % 2 == 0]
print(f"Mảng b (chỉ chứa các phần tử chẵn của a): {b}")

#cau12
total_sum = 0
for num in range(1000):
    if num % 3 == 0 or num % 5 == 0:
        total_sum += num

print(f"Tổng các số từ 0 đến 999 là bội của 3 hoặc 5 là: {total_sum}")

#cau13
def tron_mang (a,b):
  ket_qua = []
  len_a = len(a)
  len_b = len(b)
  max_len = max(len_a,len_b)
  for i in range(max_len):
    val_a = a[i] if i < len_a else 0
    val_b = b[i] if i < len_b else 0
    ket_qua.append(val_a + val_b)
  return ket_qua
a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]
print("Mảng kết quả:", tron_mang(a, b))

#cau14

#cau14a: Tạo mảng a chứa các số nguyên ngẫu nhiên.
import random

def tao_mang_ngau_nhien(m, n, min_val=0, max_val=100):
    """Tạo mảng 2 chiều mxn chứa các số nguyên ngẫu nhiên."""
    mang = []
    for _ in range(m):
        row = [random.randint(min_val, max_val) for _ in range(n)]
        mang.append(row)
    return mang

def in_mang(mang):
    """In mảng 2 chiều."""
    for row in mang:
        print([f'{x:4}' for x in row])

m = int(input("Nhập số dòng (m): "))
n = int(input("Nhập số cột (n): "))
a = tao_mang_ngau_nhien(m, n)
print("Mảng a:")
in_mang(a)
#cau14b: Xuất các phần tử thuộc dòng k.

def xuat_dong_k(mang, k):
    """Xuất các phần tử thuộc dòng k (chỉ số bắt đầu từ 0)."""
    if 0 <= k < len(mang):
        print(f"Các phần tử thuộc dòng {k}: {mang[k]}")
    else:
        print(f"Dòng {k} không hợp lệ. Mảng có {len(mang)} dòng.")
# cau14c: Xuất các phần tử thuộc cột k.

def xuat_cot_k(mang, k):
    """Xuất các phần tử thuộc cột k (chỉ số bắt đầu từ 0)."""
    if not mang:
        print("Mảng rỗng.")
        return

    n_cols = len(mang[0]) # Số cột
    if 0 <= k < n_cols:
        cot = [row[k] for row in mang]
        print(f"Các phần tử thuộc cột {k}: {cot}")
    else:
        print(f"Cột {k} không hợp lệ. Mảng có {n_cols} cột.")
#cau14d: Tìm dòng có tổng lớn nhất.

def tim_dong_tong_lon_nhat(mang):
    """Tìm dòng có tổng lớn nhất."""
    if not mang:
        print("Mảng rỗng.")
        return None, None

    max_sum = -float('inf')
    dong_max = -1
    for i, row in enumerate(mang):
        current_sum = sum(row)
        if current_sum > max_sum:
            max_sum = current_sum
            dong_max = i
    print(f"Dòng có tổng lớn nhất là dòng {dong_max} với tổng: {max_sum}")
    return dong_max, max_sum
# cau14e: Tìm cột có tích nhỏ nhất.

def tim_cot_tich_nho_nhat(mang):
    """Tìm cột có tích nhỏ nhất."""
    if not mang or not mang[0]:
        print("Mảng rỗng hoặc cột rỗng.")
        return None, None

    n_cols = len(mang[0])
    min_product = float('inf')
    cot_min = -1

    for j in range(n_cols):
        current_product = 1
        for i in range(len(mang)):
            current_product *= mang[i][j]

        if current_product < min_product:
            min_product = current_product
            cot_min = j

    print(f"Cột có tích nhỏ nhất là cột {cot_min} với tích: {min_product}")
    return cot_min, min_product
#cau14f: Xuất ra các phần tử thuộc dòng chẵn và cột lẻ trong a.

def xuat_dong_chan_cot_le(mang):
    """Xuất các phần tử thuộc dòng chẵn và cột lẻ."""
    if not mang or not mang[0]:
        print("Mảng rỗng.")
        return

    print("Các phần tử thuộc dòng chẵn và cột lẻ:")
    elements = []
    for i in range(len(mang)):
        if i % 2 == 0:  # Dòng chẵn (chỉ số 0, 2, 4, ...)
            for j in range(len(mang[0])):
                if j % 2 != 0:  # Cột lẻ (chỉ số 1, 3, 5, ...)
                    elements.append(mang[i][j])
    print(elements)
# cau14g: Tính trung bình cộng các phần tử chẵn thuộc dòng lẻ của a.

def tinh_tb_chan_dong_le(mang):
    """Tính trung bình cộng các phần tử chẵn thuộc dòng lẻ."""
    if not mang or not mang[0]:
        print("Mảng rỗng.")
        return 0

    total_sum = 0
    count = 0
    for i in range(len(mang)):
        if i % 2 != 0:  # Dòng lẻ (chỉ số 1, 3, 5, ...)
            for j in range(len(mang[0])):
                if mang[i][j] % 2 == 0:  # Phần tử chẵn
                    total_sum += mang[i][j]
                    count += 1

    if count > 0:
        average = total_sum / count
        print(f"Trung bình cộng các phần tử chẵn thuộc dòng lẻ: {average}")
        return average
    else:
        print("Không có phần tử chẵn nào thuộc dòng lẻ.")
        return 0
# cau14h: Tính trung bình cộng các phần tử thuộc biên.

def tinh_tb_phan_tu_bien(mang):
    """Tính trung bình cộng các phần tử thuộc biên."""
    if not mang or not mang[0]:
        print("Mảng rỗng.")
        return 0

    m = len(mang)
    n = len(mang[0])

    if m == 1 and n == 1:
        print(f"Trung bình cộng các phần tử thuộc biên: {mang[0][0]}")
        return mang[0][0]

    total_sum = 0
    count = 0

    # Dòng đầu và dòng cuối
    for j in range(n):
        total_sum += mang[0][j]
        count += 1
        if m > 1:
            total_sum += mang[m-1][j]
            count += 1

    # Cột đầu và cột cuối (trừ các phần tử đã tính ở dòng đầu/cuối)
    for i in range(1, m - 1):
        total_sum += mang[i][0]
        count += 1
        if n > 1:
            total_sum += mang[i][n-1]
            count += 1

    # Loại bỏ các phần tử trùng lặp nếu m > 1 và n > 1
    if m > 1 and n > 1:
        # Bốn góc được tính 2 lần, cần trừ đi 4
        # Hoặc cách đơn giản hơn: tính riêng từng cạnh và đảm bảo không trùng lặp
        # Ví dụ: (mang[0][0], mang[0][n-1], mang[m-1][0], mang[m-1][n-1])
        # đã được tính hai lần. Tuy nhiên, cách trên có thể tính được.
        # Cách an toàn hơn là dùng set để lưu các vị trí hoặc đảm bảo logic không trùng lặp

        # Reset và tính lại cẩn thận hơn để tránh trùng lặp đếm
        total_sum = 0
        count = 0

        # Dòng đầu
        for j in range(n):
            total_sum += mang[0][j]
            count += 1

        # Dòng cuối (nếu có hơn 1 dòng)
        if m > 1:
            for j in range(n):
                total_sum += mang[m-1][j]
                count += 1

        # Cột đầu (trừ 2 phần tử góc đã tính)
        for i in range(1, m - 1):
            total_sum += mang[i][0]
            count += 1

        # Cột cuối (nếu có hơn 1 cột, trừ 2 phần tử góc đã tính)
        if n > 1:
            for i in range(1, m - 1):
                total_sum += mang[i][n-1]
                count += 1


    if count > 0:
        average = total_sum / count
        print(f"Trung bình cộng các phần tử thuộc biên: {average}")
        return average
    else:
        print("Không có phần tử nào thuộc biên.")
        return 0
print("\n--- Sử dụng các hàm ---")

# Nhập dòng k để xuất
k_dong = int(input(f"Nhập chỉ số dòng k (từ 0 đến {len(a)-1}) để xuất: "))
xuat_dong_k(a, k_dong)

# Nhập cột k để xuất
k_cot = int(input(f"Nhập chỉ số cột k (từ 0 đến {len(a[0])-1}) để xuất: "))
xuat_cot_k(a, k_cot)

# Tìm dòng có tổng lớn nhất
tim_dong_tong_lon_nhat(a)

# Tìm cột có tích nhỏ nhất
tim_cot_tich_nho_nhat(a)

# Xuất các phần tử thuộc dòng chẵn và cột lẻ
xuat_dong_chan_cot_le(a)

# Tính trung bình cộng các phần tử chẵn thuộc dòng lẻ
tinh_tb_chan_dong_le(a)

# Tính trung bình cộng các phần tử thuộc biên
tinh_tb_phan_tu_bien(a)

a = [1, 2, 3, 4]
b = [5, 6, 7]

ket_qua_tron = tron_mang(a, b)
print(f"Mảng a: {a}")
print(f"Mảng b: {b}")
print(f"Mảng kết quả trộn: {ket_qua_tron}")

a_lon = [10, 20, 30]
b_lon = [1, 2, 3, 4, 5]

ket_qua_tron_2 = tron_mang(a_lon, b_lon)
print(f"\nMảng a lớn: {a_lon}")
print(f"Mảng b lớn: {b_lon}")
print(f"Mảng kết quả trộn lớn: {ket_qua_tron_2}")

#cau15a: Xây dựng cấu trúc SINHVIEN mô tả một sinh viên

class SinhVien:
    def __init__(self, ma_sinh_vien, ten, nam_sinh, diem_trung_binh):
        if len(ma_sinh_vien) != 10:
            raise ValueError("Mã sinh viên phải có 10 ký tự.")
        if len(ten) > 20:
            raise ValueError("Tên không được vượt quá 20 ký tự.")

        self.ma_sinh_vien = ma_sinh_vien
        self.ten = ten
        self.nam_sinh = nam_sinh
        self.diem_trung_binh = diem_trung_binh

    def __str__(self):
        return f"Mã SV: {self.ma_sinh_vien}, Tên: {self.ten:<20}, Năm sinh: {self.nam_sinh}, ĐTB: {self.diem_trung_binh}"


#cau15b: Cho một mảng có n sinh viên (ví dụ với n=5)

# Tạo danh sách sinh viên mẫu
sinh_vien_list = [
    SinhVien("01CS000001", "Nguyen Van A", 2003, 7.5),
    SinhVien("02DH000002", "Tran Thi Lan", 2004, 4.8),
    SinhVien("03KT000003", "Le Van B", 2002, 6.0),
    SinhVien("04SP000004", "Phan Thi Cuc", 2003, 9.2),
    SinhVien("05DH000005", "Hoang Van Danh", 2004, 3.5),
    SinhVien("06CS000006", "Phan Thi Lan", 2000, 8.1),
    SinhVien("07DH000007", "Nguyen Anh Tuan", 2004, 5.5)
]

print("Danh sách sinh viên:")
for sv in sinh_vien_list:
    print(sv)
#cau15c: Viết hàm cho biết có bao sinh viên đủ điều kiện lên lớp

def dem_sinh_vien_du_dieu_kien(danh_sach_sv):
    count = 0
    for sv in danh_sach_sv:
        if sv.diem_trung_binh >= 5.0:
            count += 1
    return count

#cau15d: Xuất các sinh viên đủ 20 tuổi.
import datetime

def xuat_sinh_vien_20_tuoi(danh_sach_sv):
    current_year = datetime.datetime.now().year
    print("\nCác sinh viên đủ 20 tuổi (tính đến năm hiện tại):")
    found = False
    for sv in danh_sach_sv:
        age = current_year - sv.nam_sinh
        if age == 20:
            print(sv)
            found = True
    if not found:
        print("Không có sinh viên nào đủ 20 tuổi.")
#cau15e: Đếm số sinh viên học hệ đại học

def dem_sinh_vien_dai_hoc(danh_sach_sv):
    count = 0
    for sv in danh_sach_sv:
        # Kiểm tra 2 ký tự 'DH' ở vị trí 2,3 (chỉ số 1 và 2)
        if len(sv.ma_sinh_vien) >= 3 and sv.ma_sinh_vien[1:3] == "DH":
            count += 1
    return count

#cau15f: Cho biết trong mảng có bao nhiêu sinh viên có tên «Lan»

def dem_sinh_vien_ten_lan(danh_sach_sv):
    count = 0
    for sv in danh_sach_sv:
        # Sử dụng .strip() để loại bỏ khoảng trắng thừa nếu có
        # So sánh tên đầy đủ, ví dụ 'Tran Thi Lan' sẽ không được tính nếu chỉ tìm 'Lan'
        # Nếu muốn tìm 'Lan' ở bất kỳ đâu trong tên, cần điều chỉnh logic
        if sv.ten.strip().endswith("Lan"):
            count += 1
    return count

#cau15g: Cho biết trong mảng có bao nhiêu sinh viên có họ «Phan»

def dem_sinh_vien_ho_phan(danh_sach_sv):
    count = 0
    for sv in danh_sach_sv:
        # Giả sử họ là phần đầu tiên của chuỗi tên
        if sv.ten.strip().startswith("Phan "):
            count += 1
    return count
#cau15e: Đếm số sinh viên học hệ đại học

def dem_sinh_vien_dai_hoc(danh_sach_sv):
    count = 0
    for sv in danh_sach_sv:
        # Kiểm tra 2 ký tự 'DH' ở vị trí 2,3 (chỉ số 1 và 2)
        if len(sv.ma_sinh_vien) >= 3 and sv.ma_sinh_vien[1:3] == "DH":
            count += 1
    return count